application.name: familie-ks-barnehagelister

server.port: 8096

spring:
  web:
    resources:
      add-mappings: false
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_JDBC_URL}
    hikari:
      maximum-pool-size: 20
      connection-test-query: "select 1"
      max-lifetime: 900000
      minimum-idle: 1
      data-source-properties.stringtype: unspecified # Nødvendig for å kunde sende en String til et json-felt i PostgresSql

management:
  endpoint.health:
    show-details: always
    probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

prosessering:
  rolle: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Gruppen teamfamilie
  continuousRunning.enabled: true
  maxantall: 10
  fixedDelayString:
    in:
      milliseconds: 5000
  delete:
    after:
      weeks: 4

BARNEHAGELISTER_SCOPE: nav:familie/v1/kontantstotte/barnehagelister
