application:
  name: familie-ks-barnehagelister

api:
  base-path: /api

server:
  port: 8096
  servlet:
    context-path: /

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ks-barnehagelister
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-test-query: "select 1"
      max-lifetime: 900000
      minimum-idle: 1
      data-source-properties.stringtype: unspecified # Nødvendig for å kunde sende en String til et json-felt i PostgresSql
management:
  endpoint.health.show-details: always
  endpoint.health.probes.enabled: true
  health.livenessState.enabled: true
  health.readinessState.enabled: true

  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  prometheus:
    metrics:
      export:
        enabled: true



no.nav.security.jwt:
  issuer.maskinporten:
    discoveryurl: ${MASKINPORTEN_WELL_KNOWN_URL}
    validation:
      optional_claims: sub,aud,nbf
#  client:
#    registration:
#      ks-barnehagelister-clientcredentials:
#        resource-url: ${BA_SAK_API_URL}
#        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
#        grant-type: client_credentials
#        scope: ${BA_SAK_SCOPE}
#        authentication:
#          client-id: ${AZURE_APP_CLIENT_ID}
#          client-secret: ${AZURE_APP_CLIENT_SECRET}
#          client-auth-method: client_secret_basic

springdoc:
  swagger-ui:
    disable-swagger-default-url: true