godkjente-leverandorer:
  leverandorer:
    - orgno: "982410339"
      navn: "VISMA ENTERPRISE AS"
    - orgno: "933287335"
      navn: "VISMA FLYT AS"
    - orgno: "832477982"
      navn: "ASSEMBLE AS"
    - orgno: "970944443"
      navn: "IST AS"

spring:
  datasource:
    hikari:
      data-source-properties:
        ssl: true
        sslmode: ${DB_SSLMODE}
        sslcert: ${DB_SSLCERT}
        sslkey: ${DB_SSLKEY_PK8}
        sslrootcert: ${DB_SSLROOTCERT}