#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n teamfamilie get secret azuread-familie-ba-sak-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: familie-ks-barnehagelister-lokal
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  preAuthorizedApplications:
    - application: familie-prosessering-lokal
      cluster: dev-gcp
      namespace: teamfamilie
  tenant: trygdeetaten.no
  secretName: azuread-familie-ks-barnehagelister-lokal
  claims:
    groups:
      - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS