apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-barnehagelister
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nais.io/restricted: "true"

spec:
  image: {{ image }}
  port: 8096
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
      cpu: 200m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ks-barnehagelister.intern.nav.no
    - https://familie-ks-barnehagelister.nav.no
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "v1/kontantstotte/barnehagelister"
          enabled: true
          product: "familie"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 680
          consumers:
            - name: "NAV"
              orgno: "889640782"
      consumes:
        - name: "nav:familie/v1/kontantstotte/barnehagelister"
  accessPolicy:
    outbound:
      rules:
        - application: familie-ks-sak
          cluster: prod-gcp
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JAVA_OPTS
      value: "-Xmx1g"
