apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-barnehagelister
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nais.io/restricted: "true"

spec:
  image: {{ image }}
  port: 8096
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
      cpu: 200m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ks-barnehagelister.intern.nav.no
    - https://familie-ks-barnehagelister.nav.no/api/kindergartenlists
    - https://familie-ks-barnehagelister.nav.no/swagger-ui/
    - https://familie-ks-barnehagelister.nav.no/swagger-ui.html
    - https://familie-ks-barnehagelister.nav.no/v3/
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "v1/kontantstotte/barnehagelister"
          separator: "/"
          delegationSource: altinn
          enabled: true
          product: "familie"
          allowedIntegrations:
            - maskinporten
          atMaxAge: 680
          accessibleForAll: true
      consumes:
        - name: "nav:familie/v1/kontantstotte/barnehagelister"
  accessPolicy:
    inbound:
      rules:
        - application: familie-prosessering
          cluster: prod-gcp
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JAVA_OPTS
      value: "-Xmx1g"
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_15 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        name: familie-ks-barnehagelister
        autoBackupHour: 2
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: familie-ks-barnehagelister
            envVarPrefix: DB
  kafka:
    pool: nav-prod
  
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Gruppen teamfamilie
      
      singlePageApplication: true