name: Build-Deploy-Preprod
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:
env:
  IMAGE: ghcr.io/navikt/familie-ks-barnehagelister:${{ github.sha }}
jobs:
  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør ktlint
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn antrun:run@ktlint
  deploy:
    name: Bygg app/image, push til github, deploy til dev-fss/prod-fss
    runs-on: ubuntu-latest
    permissions:
      packages: write
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            collector-internet.external.prod-gcp.nav.cloud.nais.io:443
            deploy.nav.cloud.nais.io:443
            europe-north1-docker.pkg.dev:443
            fulcio.sigstore.dev:443
            gcr.io:443
            github-registry-files.githubusercontent.com:443
            github.com:443
            iamcredentials.googleapis.com:443
            login.microsoftonline.com:443
            maven.pkg.github.com:443
            objects.githubusercontent.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            rekor.sigstore.dev:443
            repo.maven.apache.org:443
            sts.googleapis.com:443
            test.maskinporten.no:443
            tuf-repo-cdn.sigstore.dev:443
            test.maskinporten.no:443

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml

      - uses: nais/docker-build-push@v0
        id: docker-push
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        with:
          team: teamfamilie
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json

      - name: Deploy til dev-gcp
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/nais-preprod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}

      - name: Dependabot metadata
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
