name: Build-Deploy-Prod
on:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ks-barnehagelister:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ks-barnehagelister:latest
jobs:
  deploy:
    name: Bygg app/image, push til github, deploy til dev-fss/prod-fss
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json

      - name: Deploy til dev-gcp
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais/nais-preprod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais/nais-prod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}