name: Build-Deploy-PR
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  avslutt-andre-workflows-samme-branch:
    name: Avslutt andre workflows på samme branch
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  ktlint:
    name: Ktlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør ktlint
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn antrun:run@ktlint

  enhetstester:
    name: Enhetstester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'temurin'
          cache: 'maven'
      - name: Kjør enhetstester
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn verify -B --no-transfer-progress --settings .m2/maven-settings.xml --file pom.xml
      - name: Last opp Jacoco enhetstester rapport
        uses: actions/upload-artifact@v4
        with:
          name: jacocoUT
          path: target/jacoco/UT/jacoco.xml
          retention-days: 1
          overwrite: true